# 服务端口
server:
  port: 8080

# spring 配置
spring:
  application:
    name: wordbook-api
  # nacos 的注册地址
  cloud:
    nacos:
      discovery:
        namespace: wordbook # 这里要用 “命名空间ID”
        server-addr: centos7.server.com:8848 # 192.168.110.128:8848

# dubbo 配置
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false # 禁用 qos 监控服务，防止端口被占用
  # 注册进 nacos
  registry:
    address: nacos://centos7.server.com:8848?namespace=wordbook # nacos://192.168.110.128:8848?namespace=
    id: nacos-registry
  # 设置协议
  protocol:
    name: dubbo
